// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sewuqgwojzbcevlkjnsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNld3VxZ3dvanpiY2V2bGtqbnNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3Njk5NTMsImV4cCI6MjA3MzM0NTk1M30.9rY7p3HxSHtHBdhJfvnd4c7x4x76HgNTWBmO_puQRmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});